### PR TITLE
Support Python 3.8

### PR DESCRIPTION
**Pull request by laevilgenius**

### CODE REVIEW

**Comment by andrewgodwin** [comment]
Thanks!

**Comment by laevilgenius** [comment]
@andrewgodwin Could you make a release, so I can update channels as well?

**Comment by andrewgodwin** [comment]
Give me a bit of time to move house, and I'll get to it :)

**Comment by carltongibson** [comment]
If it would help you Andrew, I could make the commit/tag for a new release?

**Comment by andrewgodwin** [comment]
@carltongibson Go for it - asgiref should have the same automatic tag-release system as the other projects. The main reason I like to be around for a release is in case there's an undiscovered bug that needs quickly fixing..

**Comment by carltongibson** [comment]
@andrewgodwin It was just config stuff and docs, so I thought I'd risk it. _Nothing to break..._ 😝 (Now guaranteed to be here till 3am picking up the pieces! 🤞)

**Pull request merged**
