### PR TITLE
Fix Local behaviour with asyncio Task. 

### LINKED ISSUE #473: asgiref.local.Local fails to isolate changes between asyncio tasks
`asgiref.local.Local` used to isolate changes performed in asyncio tasks in pre-3.7, and stopped doing so from 3.7+. This is likely an issue, since the point of `asgiref.local.Local` compared to `threading.local` ought to be to provide locals also for asyncio concurrency.

I created a complete reproducer in [asgiref-test.py.gz](https://github.com/user-attachments/files/17235594/asgiref-test.py.gz)

I tracked the issue [to the way asgiref.local.Local sets values](https://github.com/django/asgiref/blob/main/asgiref/local.py#L27): if I read it correctly it does it in a way that it changes the dict in the previous context: it tries to do a get/update/set cycle, but it updates the mutable dict returned by `get()`,  so the side effect propagates to the state reachable before `set` is called.

Indeed, chaging that line with `storage_object = self._data.get({}).copy()` makes it behave how I would expect.

### PR DESCRIPTION
**Pull request by spanezz**
Reproduce issue #473 in asgiref's test suite

Fixes #473

### CODE REVIEW

**Review by carltongibson — COMMENTED** [review]
@spanezz That looks like a good port of the test 👍

**Comment by carltongibson** [comment]
Thanks @spanezz 👍 

The type hints need adjusting to keep mypy happy. (See CI) 

I had a glance at the different commits, but will try and reason them through this week.

**Review by carltongibson — COMMENTED** [review]
@spanezz I had a quick look. Both of these make sense. Not sure if I prefer one or the other. Option 1 is less of a change. 

Can you fix the CI, and perhaps squash the last two commits together so that option 1 and option 2 are obvious for @andrewgodwin to look at?

**Comment by carltongibson** [comment]
@spanezz You can run the type checker locally by doing (e.g.) `tox -e py311-mypy`. 

OK, everything passes with 16d4ae269b81a3bf956e43791819cacd6ce8df0a Option 1. Can I ask you to pull 7b3ce47dc2631e70b1d173d02d6f8801b1e9f0af Option 2 into a separate PR (after this one, I guess). 

I think we should go with Option 1 now, and release a v3.8.2 to fix the issue, and then we can consider whether Option 2 is worth adopting for a v3.9 at a more leisurely pace. //cc @andrewgodwin

**Comment by spanezz** [comment]
> @spanezz You can run the type checker locally by doing (e.g.) `tox -e py311-mypy`.

Thank you for the pointer! I am uncomfortable running code randomly downloaded off the internet on my devel machine, and I'm unfortunately not equipped with a suitably containerized alternative.

> OK, everything passes with [16d4ae2](https://github.com/django/asgiref/commit/16d4ae269b81a3bf956e43791819cacd6ce8df0a) Option 1. Can I ask you to pull [7b3ce47](https://github.com/django/asgiref/commit/7b3ce47dc2631e70b1d173d02d6f8801b1e9f0af) Option 2 into a separate PR (after this one, I guess).
> 
> I think we should go with Option 1 now, and release a v3.8.2 to fix the issue, and then we can consider whether Option 2 is worth adopting for a v3.9 at a more leisurely pace. //cc @andrewgodwin
> 
> I closed #477 which had the `self._data.set({**self._data.get({}), key: value})` option.

Done (I removed the simplification commit from this PR and opened #481)

**Review by andrewgodwin — APPROVED** [review]

**Comment by andrewgodwin** [comment]
This definitely seems like a pretty clean change and easier to understand than the bigger rewrite, so let's get this in.

I removed the python 3.8 tests from main - if you want to rebase on top of that so we get a clean sweep, I'm happy to merge this.

**Comment by spanezz** [comment]
> This definitely seems like a pretty clean change and easier to understand than the bigger rewrite, so let's get this in.
> 
> I removed the python 3.8 tests from main - if you want to rebase on top of that so we get a clean sweep, I'm happy to merge this.

Thanks, and done!

**Comment by andrewgodwin** [comment]
Thanks!

**Comment by andersk** [comment]
This seems to have caused a regression:

- #491

**Pull request merged**
