### PR TITLE
Drop Python 3.6

### PR DESCRIPTION
**Pull request by Andrew-Chen-Wang**
Python 3.6 EOL is soon (apparently it's today!). Dropping some compatibility. Hoping to add a PR for Local soon.

### CODE REVIEW

**Comment by Kludex** [comment]
We should remove the vendored pep as well

**Comment by andrewgodwin** [comment]
Lovely, this is a pretty significant cleanup. You love to see it.

**Comment by Andrew-Chen-Wang** [comment]
@Kludex do you mean pep562? What did I miss?

**Comment by Kludex** [comment]
Ah, you did remove it! Sorry. For some reason I didn't see the full diff before.

**Comment by Andrew-Chen-Wang** [comment]
np. It's prob because deleted files don't show a full diff, only a sliver of gray with the file name on GitHub.

**Comment by andrewgodwin** [comment]
Yeah, the diff and removal of the vendored backport all looked good to me!

**Comment by akx** [comment]
There's still this bit in `asgiref/local.py`: 

https://github.com/django/asgiref/blob/02fecb6046bb5ec0dbbad00ffcd2043e893fcea5/asgiref/local.py#L29-L30

A future PR should probably make that module use `contextvars` then :)

**Comment by Andrew-Chen-Wang** [comment]
Yes, a separate PR is needed. I lost a lot of time due to start of school, so I can't make that local PR. Sorry.

**Pull request merged**
