### PR TITLE
Flake8 fixes

### PR DESCRIPTION
**Pull request by blueyed**

### CODE REVIEW

**Comment by andrewgodwin** [comment]
We use `pyflakes` and `black` on this project - I'm not sure we need flake8 fixes when those other two are run on every commit?

**Comment by blueyed** [comment]
I'd rather use flake8 instead of pyflakes for CI.

I'm running flake8 automatically on Python files, so that's when I've noticed those issues.

**Comment by andrewgodwin** [comment]
Sure, but we currently _have_ a linting solution and I feel flake8 is a bit too picky to adopt full-time (I especially hate `# noqa`).

If you want to change the patch to add E722 to https://github.com/django/asgiref/blob/master/setup.cfg#L9, though, I'll take that.

**Comment by blueyed** [comment]
Ok.
What about `except BaseException` instead?

**Comment by carltongibson** [comment]
Closing this as stale. Please redo if you want to pick it up. Thanks.

**Pull request closed without merging**
