### PR TITLE
Update lifespan.rst

### PR DESCRIPTION
**Pull request by Kludex**

### CODE REVIEW

**Comment by andrewgodwin** [comment]
For backwards compatibility, I believe this needs to stay the same. All 2.0 versions should provide it.

**Comment by Kludex** [comment]
I think this commit 4 years ago missed this update: https://github.com/django/asgiref/commit/55e9ac45f15e89df58b1e9af54e5fe17be8f9322

Isn't it the case?

**Comment by andrewgodwin** [comment]
That's for the `www` spec, which is different to `lifespan` in terms of versioning.

**Comment by Kludex** [comment]
I see... Thanks.

**Pull request closed without merging**
