### PR TITLE
Releasing 3.8.0

### PR DESCRIPTION
**Pull request by carltongibson**
This commit prepares the release notes for a 3.8.0 release, to help clear the decks for that. 

TODO: 

- [x] Remove `(WIP)` from commit message. 
- [x] Set release date. 
- [x] ... ?

### CODE REVIEW

**Review by andrewgodwin — APPROVED** [review]

**Comment by andrewgodwin** [comment]
Thanks for getting this going - changelog looks good and matches what I can see since 3.7.2, and I don't think we need anything else for a release.

**Comment by carltongibson** [comment]
Thanks @andrewgodwin. If you're happy I can do the release in the next couple of days, if you like?

**Comment by andrewgodwin** [comment]
That sounds good to me - I'm out at a conference this week, but I'll have a little time to review anything if it comes up (or as is always the chance with a release after a while with some core changes, if it breaks compat somewhere)

**Comment by carltongibson** [comment]
OK, great. Thanks. I'll tidy this up and get it out. 

Have fun at the conference

**Comment by carltongibson** [comment]
https://pypi.org/project/asgiref/3.8.0/

**Pull request merged**
