### PR TITLE
Update StatelessServer to use ASGI v3 application. 

### LINKED ISSUE #209: Has StatelessServer been updated to the ASGI 3.0 spec?
I'm currently trying to upgrade my app from Channels 2.4.0 to Channels 3.0.0 and I'm having issues with running my worker.

After some investigation, I'm under the impression that the `StatelessServer` provided in `asgiref` hasn't been updated to the new Application specifications in ASGI 3.0.

Part of StatelessServer that is trying to instantiate an application with a scope, then call it using the receive and send arguments:
https://github.com/django/asgiref/blob/5c249e818bd5e7acef957e236535098c3aff7b42/asgiref/server.py#L87-L94

Specification for the new Application format:
https://asgi.readthedocs.io/en/latest/specs/main.html#applications

That is: `coroutine application(scope, receive, send)`

Since the Worker in Channels is based on `StatelessServer`, this is breaking the worker functionality in Channels 3.0.0.
Is this something that is in the works? Anything I can do to help with this?

### PR DESCRIPTION
**Pull request by lsaavedr**
whereas the update does not released, please fix #209 with that workaround...

### CODE REVIEW

**Comment by andrewgodwin** [comment]
I'll happily take this if you fix the lint issue!

**Comment by andrewgodwin** [comment]
I'll be happy to take this if you fix the linting errors!

**Comment by lsaavedr** [comment]
why a comma is needed? T_T

**Review by carltongibson — COMMENTED** [review]
Looks like a regression test would be easy enough... 🤔

1. Instantiate `StatelessServer` with an ASGI v3 single-callable. 
2. Call `get_or_create_application_instance()`. 

I _think_ that would crash currently but pass with this patch. 

I can take that on later or if you could add it @lsaavedr, that would be super.

**Comment by carltongibson** [comment]
I added a test case for the change. Thanks @lsaavedr. What do you think @andrewgodwin?

**Comment by lsaavedr** [comment]
Thanks @carltongibson I need to learn how to make test cases 😔

**Review by andrewgodwin — APPROVED** [review]

**Comment by andrewgodwin** [comment]
Looks good to me! I'll merge it in now.

**Comment by carltongibson** [comment]
Hey @andrewgodwin Thanks for this. 

I think we need a new release here. (Didn't add that to GHA as yet, so `setup.py build ...` and `twine upload` like the good old -days. 😀) — I want to resolve https://github.com/django/channels/pull/1567 by about mid week, thinking about a release towards the end of the week if we can coordinate. (Happy to do it if you are.)

**Comment by andrewgodwin** [comment]
I'll cut a new release now, then!

**Comment by carltongibson** [comment]
Super 😀

**Comment by andrewgodwin** [comment]
Ironically, I think I've never used twine for asgiref since I implemented the auto-release before it was required! Anyway, all done now, and we can work on getting auto-releases done later on.

**Pull request merged**
