### PR TITLE
Optional raw_path, refs #87

### PR DESCRIPTION
**Pull request by simonw**

### CODE REVIEW

**Comment by pgjones** [comment]
Could this be added to the WebSocket scope as well? Also should the spec_version be bumped?

**Comment by andrewgodwin** [comment]
I don't see a need to change the spec_version as this is an optional extra field. Agreed about WebSockets, though. Also don't say that servers have to provide `None` if they don't support it; just say they don't have to provide it (no need to make them send None rather than just leaving out the key)

**Comment by simonw** [comment]
I'm not too keen on saying "you can either set it to `None` or omit the key entirely" because, if I was implementing the spec, I'd want to know which of those two options I should pick. That's why I decided to go with documented `None`.

How about we specify that you either provide the `raw_path` key WITH a not-null value, or you omit the key entirely, but you're not allowed to return `"raw_path": None`?

**Comment by simonw** [comment]
New copy (I copied it to the websocket section as well):

HTTP___WebSocket_ASGI_Message_Format_-_Online_reStructuredText_editor

**Comment by davidism** [comment]
One somewhat confusing thing in at least Gunicorn is that while it will handle splitting `SCRIPT_NAME` and `PATH_INFO`, it will not modify `RAW_PATH`. So if the WSGI app decides to use it instead of the decoded path, it needs to do its own pre-processing otherwise routing won't work. Maybe we should specify a `RAW_SCRIPT_NAME` and `RAW_PATH_INFO` as well as the full URL?

**Comment by andrewgodwin** [comment]
@simonw Most optional fields in the current ASGI spec are defined as I suggested - optional, and if they're missing here's the default value you use. I would like to continue that.

@davidism ASGI handles the script_name/path_info thing by just providing a `root_path` option (which is essentially `SCRIPT_NAME`); the `path` that is provided is already analagous to `PATH_INFO`. I defer to you if providing a `raw_root_path` is useful; I would really hope that people aren't mounting apps under paths that they can't trust the server's decoding of, but then I do generally have too much hope.

We should at least call out the fact that this change would make `raw_path` _substantially_ different from `path` in the case of an app being mounted somewhere.

**Comment by davidism** [comment]
Ok, I misunderstood the `root_path` behavior, I don't think we need a raw version of that.

**Comment by simonw** [comment]
OK, I'll update it to fit that convention.

**Comment by simonw** [comment]
Banners_and_Alerts_and_HTTP___WebSocket_ASGI_Message_Format_-_Online_reStructuredText_editor

**Comment by andrewgodwin** [comment]
OK, this looks good to me. Unless there are any other comments, I'll merge this in.

**Pull request merged**
