### PR TITLE
Revert "Fix task cancellation propagation to subtasks when using sync…

### LINKED ISSUE #452: Regression in v3.8.0
The recent 3.8.0 release causes an intermittent test failure on Django's test suite. 

https://djangoci.com/job/pull-requests-focal/database=spatialite,label=focal-pr,python=python3.11/24499/testReport/junit/asgi.tests/ASGITest/test_disconnect_with_body/

```pytb
tests % ./runtests.py asgi.tests.ASGITest.test_disconnect_with_body
Testing against Django installed in '/Users/carlton/Projects/Django/django/django' with up to 10 processes
Found 1 test(s).
System check identified no issues (0 silenced).
F
======================================================================
FAIL: test_disconnect_with_body (asgi.tests.ASGITest.test_disconnect_with_body)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/carlton/Projects/Django/asgiref/asgiref/sync.py", line 254, in __call__
    return call_result.result()
           ^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File ".../asgiref/sync.py", line 331, in main_wrap
    result = await self.awaitable(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../django/tests/asgi/tests.py", line 374, in test_disconnect_with_body
    with self.assertRaises(asyncio.TimeoutError):
AssertionError: TimeoutError not raised

----------------------------------------------------------------------
Ran 1 test in 0.005s

FAILED (failures=1)
```

This tests disconnect handling for a request with a body. The main task processing the request is not correctly cancelled, on some runs only. (The assertion fails, with response content `{'type': 'http.response.start', 'status': 200, 'headers': [(b'Content-Type', b'text/html; charset=utf-8'), (b'Content-Length', b'12')]}` delivered, rather than the timeout.)

Bisected to 0503c2c4df06dbe56f04689fe537325f28dbbe8b by @ttys0dev for #435. 

```
0503c2c4df06dbe56f04689fe537325f28dbbe8b is the first bad commit
commit 0503c2c4df06dbe56f04689fe537325f28dbbe8b
Author: ttys0dev <126845556+ttys0dev@users.noreply.github.com>
Date:   Fri Jan 26 23:13:55 2024 -0700

    Fix task cancellation propagation to subtasks when using sync middleware (#435)

 asgiref/sync.py    |  59 +++++++++++++++-----
 tests/test_sync.py | 159 ++++++++++++++++++++++++++++++++++++++++++++++++++++-
 2 files changed, 201 insertions(+), 17 deletions(-)
```

//cc @felixxm

### PR DESCRIPTION
**Pull request by carltongibson**
… middleware (#435)"

This reverts commit 0503c2c4df06dbe56f04689fe537325f28dbbe8b.

Fixes #452. 

I don't know if there's a better way, but reviewing #435 it seemed likely there might be an issue, so it might be worth reverting and then taking a bit more time there. 

@ttys0dev do you have any thoughts?

### CODE REVIEW

**Comment by carltongibson** [comment]
@felixxm This fixed the intermittent Django failures for me. Do you want to give it a run to confirm? Thanks.

**Comment by felixxm** [comment]
TBH, I was not able to reproduce it locally :sweat_smile:

**Comment by ttys0dev** [comment]
> @ttys0dev do you have any thoughts?

Well reverting would reintroduce the original bug which prevented task cancellation from working correctly so probably reverting isn't the best option here.

> I don't know if there's a better way, but reviewing #435 it seemed likely there might be an issue, so it might be worth reverting and then taking a bit more time there.

I think the django test may have been relying on the previous incorrect task cancellation exception propagation, so the test itself might need fixing.

**Comment by carltongibson** [comment]
@ttys0dev I'd be grateful if you could take a look. 

The output sent when the test fails shows that the main process request task isn't being correctly cancelled with this change in place. 

(The timeout is for the application communicator in the test, not the app itself. The communicator gets the timeout because the app didn't return a response, because the http.disconnect was processed.)

**Comment by carltongibson** [comment]
Important to note, the original bug only affects cases where shield is being used, which is quite niche, compared to unknown scope of the issue with this patch in place.

**Review by andrewgodwin — APPROVED** [review]
It's unfortunate we have to back this one out but yes, seems like we need a way to replicate the Django test conditions in a test here.

**Comment by carltongibson** [comment]
@andrewgodwin @ttys0dev is looking now, so I suggest we hold until tomorrow. Hopefully we can work out the issue. 

If we don't have progress I can roll a 3.8.1, and we can re-add this again more leisurely.

**Comment by andrewgodwin** [comment]
Sounds like a good plan to me. This sort of thing always happens when we do fixes to the deep internals :)

**Comment by ttys0dev** [comment]
Think I have a proper fix for this in #455.

**Comment by carltongibson** [comment]
Closing in favour of #455.

**Pull request closed without merging**
